version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  chatbot_api:
    build: .
    container_name: chatbot_api
    depends_on:
      - qdrant
      - data_loader  # Đảm bảo dữ liệu đã nạp trước khi chạy API
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./config/config.yaml:/app/config/config.yaml
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    command: ["uvicorn", "retrieval_system.chatbot_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  data_loader:
    build: .
    container_name: data_loader
    depends_on:
      - qdrant
    volumes:
      - .:/app
      - ./data_ingestion/data:/app/data
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    command: ["python", "data_ingestion/data_loader.py"]
    restart: "no"  # Chạy một lần rồi dừng

volumes:
  qdrant_storage:
