data_input:
  path: ./data 

qdrant:
  host: http://qdrant:6333
  collection_name: "text_embeddings"
  threshold: 0.06
  max_results: 10

embedding_model:
  name: text-embedding-004
  vector_size: 768

gemini:
  api_key: ..
  model: gemini-2.0-flash
